sensor:
  - platform: apcupsd
    resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - nompower
      - numxfers
      - outputv
      - status
      - timeleft
      - tonbatt

# automation:
#   - id: nas_power_failure_shutdown
#     initial_state: True
#     trigger:
#       platform: state
#       entity_id: 

group:
  rack_ups:
    entities:
    - sensor.ups_battery
    - sensor.ups_input_voltage
    - sensor.ups_load
    - sensor.ups_nominal_input_voltage
    - sensor.ups_nominal_output_power
    - sensor.ups_output_voltage
    - sensor.ups_status
    - sensor.ups_time_left
    - sensor.ups_time_on_battery
    - sensor.ups_transfer_count
    name: Rack UPS