homeassistant:
  customize:
    scene.dog_food_lights:
      emulated_hue: False
      emulated_hue_name: 'Dog Food Lights'
    script.dog_food_timer:
      emulated_hue: True
      emulated_hue_name: 'Dog Food Timer'

scene:
  - name: "Dog Food Lights"
    entities:
      switch.upstairs_hall_switch: on
      switch.downstairs_hall_switch: on
      light.master_bed_light_level:
        state: on
        brightness: 255
      input_boolean.feeding_time_active: on
  

input_boolean:
  feeding_time_active:
    initial: off
    name: Dog Feeding Time
  dog_food_cooking:
    initial: off
    name: Dog Food Cooking

automation:
  - id: downstairs_off_delay_dog_feeding
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.feeding_time_active
      from: 'off'
      to: 'on'
      for:
        minutes: 2
    action:
      service: script.downstairs_off_feeding_time_reset
  - id: dog_food_timer_up
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.dog_food_cooking
      from: 'off'
      to: 'on'
      for:
        minutes: 15
    action:
      service: script.dog_food_timer_up  
        

script:
  downstairs_off_feeding_time_reset:
    sequence:
      - service: script.turn_on
        entity_id: script.downstairs_off
      - service: homeassistant.turn_off
        entity_id: input_boolean.feeding_time_active
  dog_food_timer:
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.downstairs_home
      - service: tts.amazon_polly_say
        data:
          entity_id: media_player.downstairs_home
          message: "Setting dog food timer for 15 minutes."
      - delay: 10
      - service: script.piper_allergy_shot
      - service: homeassistant.turn_on
        entity_id: input_boolean.dog_food_cooking
  piper_allergy_shot:
    sequence:
      - condition: template
        value_template: "{{is_state('calendar.pipers_allergy_shots', 'on')}}"
      - condition: time
        after: '17:00:00'
        before: '00:00:00'
      - service: tts.amazon_polly_say
        data:
          entity_id: media_player.downstairs_home
          message: "Don't forget to give Piper her allergy shot."
  dog_food_timer_up:
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.downstairs_home
      - service: tts.amazon_polly_say
        data:
          entity_id: media_player.downstairs_home
          message: "It's time to feed the dogs"
      - service: homeassistant.turn_off
        entity_id: input_boolean.dog_food_cooking
      - service: homeassistant.turn_on
        entity_id: scene.dog_food_lights