homeassistant:
  customize:
    light.living_room_light_level:
      emulated_hue: true
      friendly_name: 'Living Room Light'
    switch.downstairs_hall_switch:
      emulated_hue: true
      friendly_name: 'Downstairs Hall'
    fan.fan_level:
      emulated_hue: true
      friendly_name: 'Fan'
    switch.mantle_light_switch:
      friendly_name: 'Mantle Light'
    switch.media_center:
      emulated_hue: true
    switch.tv:
      emulated_hue: true
    switch.alexa_streaming:
      emulated_hue: true
      friendly_name: Alexa Music Streaming
    media_player.receiver:
      haaska_hidden: false
    media_player.living_room:
      haaska_name: downstairs roku

group:
  living_room:
    view: true
    name: Living Room
    icon: mdi:sofa
    entities:
    - fan.fan_level
    - light.living_room_light_level
    - switch.mantle_light_switch
    - media_player.receiver
    - cover.living_room
    - media_player.living_room

media_player:
  - platform: onkyo
    host: !secret theater_receiver_host
    name: receiver
    sources:
      video1: 'Roku'
      cd: 'TV'
      game: 'Alexa'

remote:
  - platform: itach
    name: Living Room
    host: !secret living_room_itach_host
    devices:
      - name: TV
        connaddr: 2
        commands:
          - name: "ON"
            data: "0000 006D 0022 0002 0157 00AC 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0689 0157 0056 0015 0E94"
          - name: "OFF"
            data: "0000 006D 0022 0002 0157 00AC 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0689 0157 0056 0015 0E94"
          - name: "HDMI2"
            data: "0000 006D 0022 0002 0157 00AC 0015 0016 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0016 0015 0689 0157 0056 0015 0E94"
          - name: "TV Tuner"
            data: "0000 006D 0022 0002 0157 00AC 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0015 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0040 0015 0015 0015 0040 0015 0015 0015 0015 0015 0689 0157 0056 0015 0E94"

switch:
  - platform: template
    switches:
      media_center:
        value_template: "{{is_state('media_player.receiver', 'on') and states.media_player.receiver.attributes.source == 'Roku'}}"
        turn_on:
          service: script.turn_on
          entity_id: script.watch_roku
        turn_off:
          service: script.turn_on
          entity_id: script.all_off
      alexa_streaming:
        value_template: "{{is_state('media_player.receiver', 'on') and states.media_player.receiver.attributes.source == 'Alexa'}}"
        turn_on:
          service: script.turn_on
          entity_id: script.listen_to_alexa
        turn_off:
          service: script.turn_on
          entity_id: script.all_off

      

script:
  listen_to_alexa:
    alias: Listen to Alexa
    sequence:
      - alias: turn receiver on
        service: media_player.select_source
        data:
          entity_id: media_player.receiver
          source: game
  watch_roku:
    alias: Watch Media Center
    sequence:
      - alias: Turn TV On
        service: remote.send_command
        data:
          entity_id: remote.tv
          device: 0
          command: 'ON'
      - alias: Turn receiver On
        service: media_player.select_source
        data:
          entity_id: media_player.receiver
          source: video1
      - delay:
          seconds: 8
      - alias: Switch to HDMI2
        service: remote.send_command
        data:
          entity_id: remote.tv
          device: 0
          command: 'HDMI2'
  all_off:
    alias: All Off
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.tv
          device: 0
          command: 'OFF'
      - service: media_player.turn_off
        entity_id: media_player.receiver
  welcome_home:
    alias: Welcome Home Generic
    sequence:
      - service: media_player.turn_on
        entity_id: media_player.downstairs_home
      - service: script.speak_it
        data_template:
          message: "Welcome home {{user}}."