input_boolean:
  flonase_taken:
    initial: off
    name: Take Your Flonase

automation:
  - id: flonase_reminder
    alias: Flonase Reminder
    initial_state: True
    trigger:
      - platform: time
        minutes: '/30'
        seconds: 00
    condition:
      - condition: time
        after: '08:00:00'
        before: '13:00:00'
      - condition: state
        entity_id: input_boolean.flonase_taken
        state: 'off'
      - condition: state
        entity_id: device_tracker.brian
        state: 'home'
    action:
      - service: script.speak_it
        data:
          message: "Don't forget to take your Flonase."
  - id: flonase_reset
    alias: Flonase Reset
    initial_state: True
    trigger:
      - platform: time
        at: '00:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.flonase_taken