homeassistant:
  customize:
    switch.deck_wall_light_switch:
      friendly_name: 'Deck Light'
    switch.back_yard_flood_lights_switch:
      friendly_name: 'Back Yard Flood Lights'
    group.back_yard_lights:
      emulated_hue: true

group:
  back_yard:
    entities:
    - switch.deck_wall_light_switch
    - switch.back_yard_flood_lights_switch
    - camera.back_yard
    - camera.right_side
    name: Back Yard
    view: true
  back_yard_lights:
    name: Back Yard Lights
    entities:
    - switch.deck_wall_light_switch
    - switch.back_yard_flood_lights_switch

light:
  - platform: mqtt_json
    name: Deck Stair Light
    command_topic: !secret deck_stair_lights_state_topic
    state_topic: !secret deck_stair_lights_command_topic
    effect: true
    effect_list:
      - 'solid'
      - 'bpm'
      - 'candy cane'
      - 'confetti'
      - 'cyclon rainbow'
      - 'dots'
      - 'fire'
      - 'glitter'
      - 'juggle'
      - 'lightning'
      - 'police all'
      - 'police one'
      - 'rainbow'
      - 'glitter'
      - 'rainbow with glitter'
      - 'sinelon'
      - 'twinkle'
      - 'noise'
      - 'ripple'
    brightness: true
    color_temp: true
    flash: true
    rgb: true
    retain: true