homeassistant:
  customize:
    switch.foyer_light_switch:
      friendly_name: 'Foyer Light'
    switch.porch_light_switch:
      friendly_name: 'Porch Light'
    sensor.foyer_temperature:
      icon: mdi:thermometer
    sensor.foyer_humidity:
      icon: mdi:water-percent
    sensor.foyer_lux:
      icon: mdi:lightbulb-on-outline
    binary_sensor.foyer_motion:
      device_class: motion
    sensor.foyer_real_feel:
      icon: mdi:thermometer

group:
  foyer:
    entities:
    - switch.foyer_light_switch
    - switch.porch_light_switch
    - camera.front_door
    - group.foyer_sensor
    view: true
    name: Foyer
  foyer_sensor:
    name: Foyer Sensor
    control: hidden
    entities: 
    - sensor.foyer_temperature
    - sensor.foyer_humidity
    - sensor.foyer_real_feel
    - sensor.foyer_lux
    - binary_sensor.foyer_motion
      

switch:
  - platform: mqtt
    name: "Doorbell Ring"
    command_topic: !secret doorbell_command_topic
    payload_on: "ENABLE"
    payload_off: "DISABLE"
    state_topic: !secret doorbell_status_topic
    optimistic: false
    retain: true
sensor:
  - platform: mqtt
    state_topic: !secret foyer_sensor_state_topic
    name: Foyer Humidity
    unit_of_measurement: '%'
    value_template: '{{value_json.humidity | round(1)}}'
  - platform: mqtt
    state_topic: !secret foyer_sensor_state_topic
    name: Foyer Temperature
    unit_of_measurement: 'F'
    value_template: '{{value_json.temperature | round(1)}}'
  - platform: mqtt
    state_topic: !secret foyer_sensor_state_topic
    name: Foyer Lux
    unit_of_measurement: 'LUX'
    value_template: '{{value_json.ldr}}'
  - platform: mqtt
    state_topic: !secret foyer_sensor_state_topic
    name: Foyer Real Feel
    unit_of_measurement: 'F'
    value_template: '{{value_json.heatIndex | round(1)}}'

binary_sensor:
  - platform: mqtt
    name: Foyer Motion
    state_topic: !secret foyer_sensor_state_topic
    value_template: '{{value_json.motion}}'
    payload_on: 'motion detected'
    payload_off: 'standby'

camera:
  - platform: generic
    name: Front Door
    still_image_url: !secret front_door_camera_snapshot_url
