homeassistant:
  customize:
    switch.foyer_light_switch:
      friendly_name: 'Foyer Light'
      emulated_hue: true
    switch.porch_light_switch:
      friendly_name: 'Porch Light'
      emulated_hue: true
    sensor.foyer_temperature:
      icon: mdi:thermometer
    sensor.foyer_humidity:
      icon: mdi:water-percent
    sensor.foyer_lux:
      icon: mdi:lightbulb-on-outline
    binary_sensor.foyer_motion:
      device_class: motion
    sensor.foyer_real_feel:
      icon: mdi:thermometer
    lock.front_door_locked:
      friendly_name: 'Lock Status'
      emulated_hue: true
    sensor.front_door_lock_battery:
      friendly_name: Battery Level

group:
  foyer:
    entities:
    - switch.foyer_light_switch
    - switch.porch_light_switch
    - camera.front_door
    - group.foyer_sensor
    - group.front_door_lock
    view: true
    name: Foyer
  front_door_lock:
    name: Front Door Lock
    entities:
      - lock.front_door_locked
      - sensor.front_door_lock_battery
      - sensor.front_door_access_control
      - sensor.front_door_alarm_level
      - sensor.front_door_alarm_type
      - sensor.front_door_burglar
      - sensor.front_door_power_management
      - sensor.front_door_sourcenodeid
      - sensor.front_door_system
  foyer_sensor:
    name: Foyer Sensor
    control: hidden
    entities: 
    - sensor.foyer_temperature
    - sensor.foyer_humidity
    - sensor.foyer_real_feel
    - sensor.foyer_lux
    - binary_sensor.foyer_motion
      

switch:
  - platform: mqtt
    name: "Doorbell Ring"
    command_topic: !secret doorbell_command_topic
    payload_on: "ENABLE"
    payload_off: "DISABLE"
    state_topic: !secret doorbell_status_topic
    optimistic: false
    retain: true
sensor:
  - platform: mqtt
    state_topic: !secret foyer_sensor_state_topic
    name: Foyer Humidity
    unit_of_measurement: '%'
    value_template: '{{value_json.humidity | round(1)}}'
  - platform: mqtt
    state_topic: !secret foyer_sensor_state_topic
    name: Foyer Temperature
    unit_of_measurement: 'F'
    value_template: '{{value_json.temperature | round(1)}}'
  - platform: mqtt
    state_topic: !secret foyer_sensor_state_topic
    name: Foyer Lux
    unit_of_measurement: 'LUX'
    value_template: '{{value_json.ldr}}'
  - platform: mqtt
    state_topic: !secret foyer_sensor_state_topic
    name: Foyer Real Feel
    unit_of_measurement: 'F'
    value_template: '{{value_json.heatIndex | round(1)}}'
  - platform: template
    sensors:
      front_door_lock_battery:
        value_template: '{{states.zwave.front_door.attributes.battery_level}}'
        unit_of_measurement: '%'

binary_sensor:
  - platform: mqtt
    name: Foyer Motion
    state_topic: !secret foyer_sensor_state_topic
    value_template: '{{value_json.motion}}'
    payload_on: 'motion detected'
    payload_off: 'standby'

camera:
  - platform: generic
    name: Front Door
    still_image_url: !secret front_door_camera_snapshot_url
