homeassistant:
  customize:
    switch.garage_light_switch:
      friendly_name: 'Garage Light'
    switch.driveway_flood_lights_switch:
      friendly_name: 'Driveway Flood Lights'
    lock.garage_door_locked:
      friendly_name: 'Lock Status'
      emulated_hue: true
    sensor.garage_door_lock_battery:
      friendly_name: Battery Level

group:
  garage:
    entities:
    - camera.left_side
    - camera.driveway
    - switch.garage_light_switch
    - switch.driveway_flood_lights_switch
    - group.garage_door_lock
    view: true
    name: Garage
    icon: mdi:car
  garage_door_lock:
    name: Garage Door Lock
    entities:
      - lock.garage_door_locked
      - sensor.garage_door_lock_battery
      - sensor.garage_door_access_control
      - sensor.garage_door_alarm_level
      - sensor.garage_door_alarm_type
      - sensor.garage_door_burglar
      - sensor.garage_door_power_management
      - sensor.garage_door_sourcenodeid
      - sensor.garage_door_system

automation:
  - id: front_floods_on_dusk
    alias: Front Floods On Dusk
    initial_state: True
    trigger:
      platform: sun
      event: sunset
      offset: '-00:45:00'
    action:
      service: switch.turn_on
      entity_id: switch.driveway_flood_lights_switch
  - id: front_floods_off_dawn
    alias: Front Floods Off Dawn
    initial_state: True
    trigger:
      platform: sun
      event: sunrise
      offset: '01:00:00'
    action:
      service: switch.turn_off
      entity_id: switch.driveway_flood_lights_switch