homeassistant:
  customize:
    switch.kitchen_light_switch:
      friendly_name: 'Kitchen Light'
      emulated_hue: true
    switch.kitchen_entry_switch:
      friendly_name: 'Kitchen Entry'
      emulated_hue: true
    scene.cooking:
      emulated_hue: true
      emulated_hue_name: 'Cooking Time'
    group.kitchen_led_strips:
      visible: false
      emulated_hue: true
    light.overcabinet_lights:
      haaska_hidden: false
    sensor.kitchen_temperature:
      icon: mdi:thermometer
      haaska_hidden: false
    sensor.kitchen_humidity:
      icon: mdi:water-percent
    sensor.kitchen_lux:
      icon: mdi:lightbulb-on-outline
    binary_sensor.kitchen_motion:
      device_class: motion
    sensor.kitchen_real_feel:
      icon: mdi:thermometer

group:
  Kitchen:
    entities:
    - switch.kitchen_light_switch
    - switch.kitchen_entry_switch
    - switch.counter_lights
    - light.overcabinet_lights
    - group.kitchen_sensor
    name: Kitchen
    view: true
    icon: mdi:stove
  kitchen_led_strips:
    entities:
      - switch.counter_lights
      - light.overcabinet_lights
    name: Kitchen LED Strips
  floorplan:
    entities:
      - binary_sensor.floorplan
    name: Floorplan
    control: hidden
  kitchen_sensor:
    name: Kitchen Sensor
    control: hidden
    entities: 
    - sensor.kitchen_temperature
    - sensor.kitchen_humidity
    - sensor.kitchen_real_feel
    - sensor.kitchen_lux
    - binary_sensor.kitchen_motion

scene:
  - name: Cooking
    entities:
      switch.kitchen_light_switch: on
      switch.counter_lights: on
      light.overcabinet_lights: 
        state: on
        brightness: 200
        effect: 'solid'
        color_name: 'white'

switch:
  - platform: mqtt
    name: "Counter Lights"
    state_topic: !secret counter_lights_state_topic
    command_topic: !secret counter_lights_command_topic
    qos: 0
    payload_on: "on"
    payload_off: "off"
    retain: false
light:
  - platform: mqtt_json
    name: Overcabinet Lights
    command_topic: !secret overcabinet_lights_state_topic
    state_topic: !secret overcabinet_lights_command_topic
    effect: true
    effect_list:
      - 'solid'
      - 'bpm'
      - 'candy cane'
      - 'confetti'
      - 'cyclon rainbow'
      - 'dots'
      - 'fire'
      - 'glitter'
      - 'juggle'
      - 'lightning'
      - 'police all'
      - 'police one'
      - 'rainbow'
      - 'glitter'
      - 'rainbow with glitter'
      - 'sinelon'
      - 'twinkle'
      - 'noise'
      - 'ripple'
    brightness: true
    color_temp: true
    flash: true
    rgb: true
    retain: true

sensor:
  - platform: mqtt
    state_topic: !secret kitchen_sensor_state_topic
    name: Kitchen Humidity
    unit_of_measurement: '%'
    value_template: '{{value_json.hum | round(1)}}'
  - platform: mqtt
    state_topic: !secret kitchen_sensor_state_topic
    name: Kitchen Temperature
    unit_of_measurement: 'F'
    value_template: '{{value_json.temp | round(1)}}'
  - platform: mqtt
    state_topic: !secret kitchen_sensor_state_topic
    name: Kitchen Lux
    unit_of_measurement: 'LUX'
    value_template: '{{value_json.ldr}}'
  - platform: mqtt
    state_topic: !secret kitchen_sensor_state_topic
    name: Kitchen Real Feel
    unit_of_measurement: 'F'
    value_template: '{{value_json.htIdx | round(1)}}'

binary_sensor:
  - platform: mqtt
    name: Kitchen Motion
    state_topic: !secret kitchen_sensor_state_topic
    value_template: '{{value_json.motion}}'
    payload_on: 'motion detected'
    payload_off: 'standby'