group:
  upstairs_hall:
    view: true
    name: Upstairs Hall
    entities:
      - switch.salt_lamp

automation:
  - id: salt_lamp_on_dusk
    alias: Salt Lamp On Dusk
    initial_state: True
    trigger:
      platform: sun
      event: sunset
      offset: '-00:45:00'
    action:
      service: switch.turn_on
      entity_id: switch.salt_lamp
  - id: salt_lamp_off
    alias: Salt Lamp Off 1AM
    initial_state: True
    trigger:
      platform: time
      at: '01:00:00'
    action:
      service: switch.turn_off
      entity_id: switch.salt_lamp